version: "3"
services:
  java-change-operations:
    build:
      context: .
    ports:
      - "8081:8080"
    networks:
      - java-mysql
    depends_on:
      - mysqldb
      - java-currency-exchange-rates

  java-currency-exchange-rates:
    build:
      context: ./Currency-exchange-rates
    container_name: java-currency-exchange-rates
    ports:
      - "8080:8080"
    networks:
      - java-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    container_name: mysqldb
    networks:
      - java-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=java_operation_change  

networks:
  java-mysql:
    name: java-mysql
